/* Generated By:JavaCC: Do not edit this line. JasminParserConstants.java */
package wt.parser.jasmin;

public interface JasminParserConstants {

  int EOF = 0;
  int SEP = 5;
  int SINGLE_LINE_COMMENT = 7;
  int DCATCH = 9;
  int DCLASS = 10;
  int DEND = 11;
  int DFIELD = 12;
  int DLIMIT = 13;
  int DLINE = 14;
  int DMETHOD = 15;
  int DSET = 16;
  int DSUPER = 17;
  int DSOURCE = 18;
  int DTHROWS = 19;
  int DVAR = 20;
  int DIMPLEMENTS = 21;
  int DINTERFACE = 22;
  int TO = 23;
  int USING = 24;
  int IS = 25;
  int FROM = 26;
  int METHOD = 27;
  int ABSTRACT = 28;
  int FINAL = 29;
  int INTERFACE = 30;
  int NATIVE = 31;
  int PRIVATE = 32;
  int PROTECTED = 33;
  int PUBLIC = 34;
  int STATIC = 35;
  int SYNCHRONIZED = 36;
  int TRANSIENT = 37;
  int VOLATILE = 38;
  int LOOKUPSWITCH = 39;
  int TABLESWITCH = 40;
  int DEFAULT_BRANCH = 41;
  int EQ = 42;
  int COLON = 43;
  int Int = 44;
  int SIGN = 45;
  int DECIMAL_LITERAL = 46;
  int HEX_LITERAL = 47;
  int OCTAL_LITERAL = 48;
  int Num = 49;
  int EXPONENT = 50;
  int Str = 51;
  int Word = 52;
  int LETTER = 53;
  int DIGIT = 54;
  int SPECIAL_CHAR = 55;

  int DEFAULT = 0;
  int MIDLINE = 1;
  int IN_SINGLE_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\n\"",
    "\";\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 8>",
    "\".catch\"",
    "\".class\"",
    "\".end\"",
    "\".field\"",
    "\".limit\"",
    "\".line\"",
    "\".method\"",
    "\".set\"",
    "\".super\"",
    "\".source\"",
    "\".throws\"",
    "\".var\"",
    "\".implements\"",
    "\".interface\"",
    "\"to\"",
    "\"using\"",
    "\"is\"",
    "\"from\"",
    "\"method\"",
    "\"abstract\"",
    "\"final\"",
    "\"interface\"",
    "\"native\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"static\"",
    "\"synchronized\"",
    "\"transient\"",
    "\"volatile\"",
    "\"lookupswitch\"",
    "\"tableswitch\"",
    "\"default\"",
    "\"=\"",
    "\":\"",
    "<Int>",
    "<SIGN>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<Num>",
    "<EXPONENT>",
    "<Str>",
    "<Word>",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIAL_CHAR>",
  };

}
